apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  db: QnVkZ3lfcHJvZHVjdGlvbg==
  username: QnVkZ3k=
  password: cGFzc3dvcmQxMjM=
  rails-master-key: YzBkYTU1NzU0YTAwMjc1NDRiZmI5ZDA1YzI5NDQ1MjA=
